package com.example.contestifyme.ui.theme

import androidx.compose.ui.graphics.Color


val md_theme_light_primary = Color(0xFF295EA7)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFD6E3FF)
val md_theme_light_onPrimaryContainer = Color(0xFF001B3E)
val md_theme_light_secondary = Color(0xFF006C4E)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFF87F8C9)
val md_theme_light_onSecondaryContainer = Color(0xFF002115)
val md_theme_light_tertiary = Color(0xFF006B5C)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFF77F8DF)
val md_theme_light_onTertiaryContainer = Color(0xFF00201B)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFDFBFF)
val md_theme_light_onBackground = Color(0xFF1A1B1E)
val md_theme_light_surface = Color(0xFFFDFBFF)
val md_theme_light_onSurface = Color(0xFF1A1B1E)
val md_theme_light_surfaceVariant = Color(0xFFE0E2EC)
val md_theme_light_onSurfaceVariant = Color(0xFF44474E)
val md_theme_light_outline = Color(0xFF74777F)
val md_theme_light_inverseOnSurface = Color(0xFFF1F0F4)
val md_theme_light_inverseSurface = Color(0xFF2F3033)
val md_theme_light_inversePrimary = Color(0xFFA9C7FF)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFF295EA7)
val md_theme_light_outlineVariant = Color(0xFFC4C6D0)
val md_theme_light_scrim = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFFA9C7FF)
val md_theme_dark_onPrimary = Color(0xFF003064)
val md_theme_dark_primaryContainer = Color(0xFF00468C)
val md_theme_dark_onPrimaryContainer = Color(0xFFD6E3FF)
val md_theme_dark_secondary = Color(0xFF6ADBAE)
val md_theme_dark_onSecondary = Color(0xFF003827)
val md_theme_dark_secondaryContainer = Color(0xFF00513A)
val md_theme_dark_onSecondaryContainer = Color(0xFF87F8C9)
val md_theme_dark_tertiary = Color(0xFF57DBC3)
val md_theme_dark_onTertiary = Color(0xFF00382F)
val md_theme_dark_tertiaryContainer = Color(0xFF005045)
val md_theme_dark_onTertiaryContainer = Color(0xFF77F8DF)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF1A1B1E)
val md_theme_dark_onBackground = Color(0xFFE3E2E6)
val md_theme_dark_surface = Color(0xFF1A1B1E)
val md_theme_dark_onSurface = Color(0xFFE3E2E6)
val md_theme_dark_surfaceVariant = Color(0xFF44474E)
val md_theme_dark_onSurfaceVariant = Color(0xFFC4C6D0)
val md_theme_dark_outline = Color(0xFF8E9099)
val md_theme_dark_inverseOnSurface = Color(0xFF1A1B1E)
val md_theme_dark_inverseSurface = Color(0xFFE3E2E6)
val md_theme_dark_inversePrimary = Color(0xFF295EA7)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFFA9C7FF)
val md_theme_dark_outlineVariant = Color(0xFF44474E)
val md_theme_dark_scrim = Color(0xFF000000)


val seed = Color(0xFF232D3F)
val CustomColor1 = Color(0xFFF05941)
val CustomColor2 = Color(0xFFBE3144)
val light_CustomColor1 = Color(0xFFB12C19)
val light_onCustomColor1 = Color(0xFFFFFFFF)
val light_CustomColor1Container = Color(0xFFFFDAD4)
val light_onCustomColor1Container = Color(0xFF400200)
val dark_CustomColor1 = Color(0xFFFFB4A6)
val dark_onCustomColor1 = Color(0xFF670600)
val dark_CustomColor1Container = Color(0xFF8F1103)
val dark_onCustomColor1Container = Color(0xFFFFDAD4)
val light_CustomColor2 = Color(0xFFB2283C)
val light_onCustomColor2 = Color(0xFFFFFFFF)
val light_CustomColor2Container = Color(0xFFFFDADA)
val light_onCustomColor2Container = Color(0xFF40000B)
val dark_CustomColor2 = Color(0xFFFFB3B5)
val dark_onCustomColor2 = Color(0xFF680018)
val dark_CustomColor2Container = Color(0xFF900827)
val dark_onCustomColor2Container = Color(0xFFFFDADA)
